tasks:
  - init: |
      docker-compose build
      python3 -m venv pythonenv
      source pythonenv/bin/activate
      pip install -r requirements.txt
      pip install pytest
    command: |
      echo ${HTW_SETTINGS_JSON} > config.json
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
