tasks:
  - init: |
      docker-compose build
      python3 -m venv pythonenv
      source pythonenv/bin/activate
      poetry install
      echo ${HTW_SETTINGS_JSON} > config.json
    command: |
      echo "Run the command by doing executing 'python -m htw -d' or 'docker-compose up --build'."
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
