image: gitpod/workspace-python:latest
tasks:
  - init: |
      docker-compose build
      poetry install
    command: sh ./.devcontainer/postCreateCommand.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
