[tool.pylint.format]
indent-string = "\t"
max-line-length = 120

[tool.pylint.design]
max-attributes = 10

[tool.pylint.logging]
# E0401 - Doesn't seem to work for me.
# R1732 - consider-using-with. Disabled as I didn't intend the output to be temporary.
disable = ["E0401", "R1732"]
