name: Deploy the Hot-this-week!

on:
  schedule:
  - cron: "0 14 * * 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Craft config
      run: echo "${{ secrets.HTK_CONFIG }}" > ${PWD}/config.json && docker run -v ${PWD}/config.json:/opt/app/config.json ghcr.io/soup-bowl/hot-this-week:edge -d
