name: Compile edge container

on:
  push:
    branches: [ edge ]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "htw/**"
      - "tests/**"
      - ".github/workflows/docker-image-edge.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Python get
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Grab Dependencies
      run: pip install -r requirements.txt && pip install pytest

    - name: Run unit tests
      run: pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Authenticate ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push image
      run: docker buildx build --push --tag ghcr.io/soup-bowl/hot-this-week:edge --platform linux/amd64,linux/arm64,linux/arm/v7 .
