name: Compile mainline container

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "htw/**"
      - ".github/workflows/docker-image-main.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Python get
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Grab Dependencies
      run: pip install -r requirements.txt && pip install pytest

    - name: Run unit tests
      run: pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build & Push to Dockerhub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: soupbowl/hot-this-week:latest,ghcr.io/soup-bowl/hot-this-week:latest
        platforms: linux/amd64,linux/arm64
