name: Compile mainline container

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "htw/**"
      - ".github/workflows/docker-image-main.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Python get
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
      
    - name: Grab Dependencies
      run: pip install -r requirements.txt && pip install pytest

    - name: Run unit tests
      run: pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Avast, we got stuff to do!
      uses: actions/checkout@v2

    - name: Rooty-tooty, make the booty!
      run: docker build . --file Dockerfile --tag ghcr.io/soup-bowl/hot-this-week:latest
      
    - name: Are you the right scallywag?
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Yeet onto The Flying Packageman ship.
      run: docker push ghcr.io/soup-bowl/hot-this-week:latest
