name: Compile container

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rooty-tooty make the booty
      run: docker build . --file Dockerfile --tag hot-this-week:$(date +%s)
